[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "NuRadioMC"
version = "2.1.0"
authors = ["Christian Glaser"]
homepage = "https://github.com/nu-radio/NuRadioMC"
license = "GPL-3.0-or-later"
packages = [
    {include = "NuRadioMC"},
    {include = "NuRadioReco"}
]
description = "A Monte Carlo simulation package for radio neutrino detectors and reconstruction framework for radio detectors of high-energy neutrinos and cosmic-rays."
# classifiers = ["License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)"]

[tool.poetry.dependencies]
numpy = "*"
scipy = "*"
tinydb = ">=4.1.1"
tinydb-serialization = ">=2.1"
aenum = "*"
astropy = "*"
radiotools = ">=0.2"
cython = "*"
dash = ">=2.0"
future = "*"
h5py = "*"
peakutils = "*"
pymongo = "*"
pyyaml = "*"
sphinx = "*"
uproot = "4.1.1"
awkward = "*"
python = "^3.6"
# proposal = {version="6.1.6", optional=true}
matplotlib = "*"
toml = ">=0.10.2"
importlib-metadata = {version = ">=4.8.1", python = "<3.8"}
