name: Build and publish

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.4.0
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Cache pip
      uses: actions/cache@v2
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('NuRadioMC/test/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    
    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry 
      # poetry recommends using curl to install - probably doesn't make a difference though?
    
    - name: Build NuRadioMC # let's always build - maybe this will occasionally catch errors
      run: poetry build
    
    - name: Publish distribution 📦 to Test PyPI
      if: ${{ github.ref == 'refs/heads/develop'}} # only runs if the push is to develop
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
    
    - name: Publish distribution 📦 to PyPI
      if: ${{ github.ref == 'refs/heads/master'}} # only runs if the push is to master
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}