name: Unit tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Cache pip
      uses: actions/cache@v2
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('NuRadioMC/test/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        sudo apt-get install libgsl-dev
        python -m pip install --upgrade pip
        pip install flake8 pytest
        export GSLDIR=$(gsl-config --prefix)
        python install_dev.py --install --dev proposal --no-interactive
        export PYTHONPATH=$PWD:$PYTHONPATH
        
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: "Single event test (South Pole)"
      run: |
        NuRadioMC/test/SingleEvents/test_build.sh
    - name: Single event test (Moore's Bay)
      run: |
        NuRadioMC/test/SingleEvents/validate_MB.sh
    - name: Single event test (ARZ)
      run: |
        NuRadioMC/test/SingleEvents/validate_ARZ.sh
    - name: Test Numba version of ARZ
      run: |
        pip install numba
        NuRadioMC/test/SingleEvents/validate_ARZ.sh
    - name: Signal generation test
      run : |
              NuRadioMC/test/SignalGen/test_build.sh
    - name: "Signal propagation tests"
      run: |
           NuRadioMC/test/SignalProp/run_signal_test.sh
    - name: "Test Veff example"
      run: |
        NuRadioMC/test/examples/test_veff_example.sh
    - name: "Test calibration pulser example"
      run: |
        NuRadioMC/test/examples/test_cal_pulser_example.sh
    - name: "Test webinar examples"
      run: |
        pip install proposal==6.1.6
        NuRadioMC/test/examples/test_webinar.sh
    - name: "Veff test"
      run: |
        NuRadioMC/test/Veff/1e18eV/test_build.sh
    - name: "Veff test with noise and phased array"
      run: |
        NuRadioMC/test/Veff/1e18eV/test_build_noise.sh
    - name: "Atmospheric Aeff test" 
      run: |
        pip install proposal==6.1.6
        NuRadioMC/test/atmospheric_Aeff/1e18eV/test_build.sh
    - name: "Tiny reconstrucution"
      run: |
        NuRadioReco/test/tiny_reconstruction/testTinyReconstruction.sh
    - name: "Trigger tests"
      run: |
        NuRadioReco/test/trigger_tests/run_trigger_test.sh
    - name: "Test all examples"
      run: |
        NuRadioReco/test/test_examples.sh
